// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVFSiTPZ2_H7A3rYf5055AP4WtypQIA_c',
    appId: '1:1055908299914:web:e176df77ec7452833fd973',
    messagingSenderId: '1055908299914',
    projectId: 'fractal-vault',
    authDomain: 'fractal-vault.firebaseapp.com',
    storageBucket: 'fractal-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupU16Hdj1aDI3YU-izuJdDis7Vzlst_A',
    appId: '1:1055908299914:android:9a20a5e1918806013fd973',
    messagingSenderId: '1055908299914',
    projectId: 'fractal-vault',
    storageBucket: 'fractal-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgSCNG1tgvkGvqCbFsbP9Fn-zKnN5ZIvQ',
    appId: '1:1055908299914:ios:9128565d6a9e292e3fd973',
    messagingSenderId: '1055908299914',
    projectId: 'fractal-vault',
    storageBucket: 'fractal-vault.firebasestorage.app',
    iosClientId: '1055908299914-f1mvuas1u1otm178nnrp59dgfqgsdotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fractalVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgSCNG1tgvkGvqCbFsbP9Fn-zKnN5ZIvQ',
    appId: '1:1055908299914:ios:9128565d6a9e292e3fd973',
    messagingSenderId: '1055908299914',
    projectId: 'fractal-vault',
    storageBucket: 'fractal-vault.firebasestorage.app',
    iosClientId: '1055908299914-f1mvuas1u1otm178nnrp59dgfqgsdotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fractalVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVFSiTPZ2_H7A3rYf5055AP4WtypQIA_c',
    appId: '1:1055908299914:web:e7b0419a178679313fd973',
    messagingSenderId: '1055908299914',
    projectId: 'fractal-vault',
    authDomain: 'fractal-vault.firebaseapp.com',
    storageBucket: 'fractal-vault.firebasestorage.app',
  );
}
