// Location: lib/main.dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart'; // We need this package for the font!
import 'package:firebase_core/firebase_core.dart'; // Required for Firebase Engine
import 'firebase_options.dart'; // The file generated by flutterfire configure
import 'screens/login_screen.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  // 1. Ensure Flutter bindings are ready before interacting with native code
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  // 2. Wake up the Firebase Engine
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the app
  runApp(const FractalVaultApp());
}

class FractalVaultApp extends StatelessWidget {
  const FractalVaultApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fractal Vault',
      debugShowCheckedModeBanner: false, // Hides the annoying debug corner ribbon
      
      // *** TISTA'S DESIGN THEME ***
      theme: ThemeData(
        useMaterial3: true,
        
        // Setting the overall 'Inter' font for clarity and trust
        textTheme: GoogleFonts.interTextTheme(Theme.of(context).textTheme),
        
        // The overall grounded, secure backdrop
        scaffoldBackgroundColor: const Color(0xFF33D1EE), // Now it's Cyan!

        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xFF0D2137), // Deep Navy Blue (Trust)
          onPrimary: Colors.white,
          secondary: Color(0xFF33D1EE), // Modern Cyan (Tech Accent)
          onSecondary: Colors.white,
          error: Colors.redAccent,
          onError: Colors.white,
          surface: Colors.white,
          onSurface: Color(0xFF0D2137), // Dark text on light backgrounds
        ),
      ),
      home: const LoginScreen(), 
    );
  }
}