// Location: lib/main.dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart'; // We need this package for the font!
import 'package:firebase_core/firebase_core.dart'; // Required for Firebase Engine
import 'package:firebase_auth/firebase_auth.dart'; // 🔥 REQUIRED FOR THE AUTH WRAPPER
import 'firebase_options.dart'; // The file generated by flutterfire configure
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:screen_protector/screen_protector.dart';
import 'package:shared_preferences/shared_preferences.dart'; // 🔥 NEEDED TO CHECK SAVED SETTINGS

// --- YOUR SCREENS ---
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart'; // 🔄 CHANGE THIS to whatever your main navigation screen is called

void main() async {
  // 1. Ensure Flutter bindings are ready before interacting with native code
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  
  // 2. Wake up the Firebase Engine
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 🔥 3. LOAD STEALTH MODE ON APP BOOT
  try {
    final prefs = await SharedPreferences.getInstance();
    final bool isStealthOn = prefs.getBool('stealthMode') ?? false;
    
    if (isStealthOn) {
      await ScreenProtector.preventScreenshotOn();
      await ScreenProtector.protectDataLeakageWithColor(Colors.black);
    }
  } catch (e) {
    debugPrint("Stealth Mode Boot Error: $e");
  }

  // 4. Run the app
  runApp(const FractalVaultApp());
}

class FractalVaultApp extends StatelessWidget {
  const FractalVaultApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fractal Vault',
      debugShowCheckedModeBanner: false, // Hides the annoying debug corner ribbon
      
      // *** TISTA'S DESIGN THEME ***
      theme: ThemeData(
        useMaterial3: true,
        
        // Setting the overall 'Inter' font for clarity and trust
        textTheme: GoogleFonts.interTextTheme(Theme.of(context).textTheme),
        
        // The overall grounded, secure backdrop
        scaffoldBackgroundColor: const Color(0xFF33D1EE), // Now it's Cyan!

        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xFF0D2137), // Deep Navy Blue (Trust)
          onPrimary: Colors.white,
          secondary: Color(0xFF33D1EE), // Modern Cyan (Tech Accent)
          onSecondary: Colors.white,
          error: Colors.redAccent,
          onError: Colors.white,
          surface: Colors.white,
          onSurface: Color(0xFF0D2137), // Dark text on light backgrounds
        ),
      ),
      
      // 🔥 THE FIX: The Auth Wrapper replaces the hardcoded LoginScreen
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // 1. While Firebase is checking the token, show a secure loading spinner
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              backgroundColor: Color(0xFF0D2137), // Using your Navy Blue
              body: Center(
                child: CircularProgressIndicator(color: Color(0xFF33D1EE)), // Cyan spinner
              ),
            );
          }

          // 2. If the user has a valid session token, let them straight into the Vault
          if (snapshot.hasData) {
            return const DashboardScreen(); // 🔄 Change this if your main hub is named differently!
          }

          // 3. If there is no token (or they clicked Terminate Session), show Login
          return const LoginScreen();
        },
      ),
    );
  }
}